# Generated by Django 5.2.9 on 2026-06-01 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_checklistitem_taskactivity_taskattachment_and_more'),
        ('workspace', '0003_department_folder_spaceitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='workspace.folder'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['folder'], name='project_pro_folder__d516bf_idx'),
        ),
    ]
